### ISSUE TITLE
`#main` anchor issue on Attributes page

### ISSUE THREAD

**Issue by Kyle-Ye** [apple/swift-docc-render#788]
### Location

https://docs.swift.org/swift-book/documentation/the-swift-programming-language/attributes/#UIApplicationMain

### Description

This issue is highlighted by TSPL content changes in apple/swift-book#212 

Click `main` link on `UIApplicationMain` section does not navigate us to the right place.

This is the same effect if we browse `https://docs.swift.org/swift-book/documentation/the-swift-programming-language/attributes/#main` directly.

### Additional Details

Other anchor on Attributes page seems fine. But `#main` is not work here. Maybe there is some potential conflict in `swift-docc-render` or `javascript/css` conflict in `swift.org` website.

rdar://110847532

**Comment by mportiz08** [comment]
Hm. This is most likely a conflict with an existing `id="main"` html element used by the renderer. 😢

In the short term, it may be easiest to just rename the one assigned by the renderer to avoid this conflict.

In the longer term, we may want to enhance the way that DocC generates "anchor" values so that it is more unlikely to ever conflict with any id values assigned by the renderer for UI elements, although they will naturally become less "guessable" (probably not a huge issue now that we have clickable headings that will pre-populate the URL with the right value). Additionally, this may be needed for the scenario where there are multiple sections with the same title since they will probably get the same anchor today and have a similar issue.

**Comment by mportiz08** [comment]
This is the likely culprit: https://github.com/apple/swift-docc-render/blob/3bafe3cc07a3d132148f96c8f2ab6984b5084b82/src/components/DocumentationTopic.vue#L18

**Comment by Kyle-Ye** [comment]
> Hm. This is most likely a conflict with an existing `id="main"` html element used by the renderer. 😢
> 
> In the short term, it may be easiest to just rename the one assigned by the renderer to avoid this conflict.

+1 for me.

> Additionally, this may be needed for the scenario where there are multiple sections with the same title since they will probably get the same anchor today and have a similar issue.

I do not think we should have to consider this as an issue.

This issue has existed everywhere in the web world.

eg. GitHub's markdown preview anchor support (eg. [UnderscoredAttributes#_used](https://github.com/apple/swift/blob/main/docs/ReferenceGuides/UnderscoredAttributes.md#_used))
and too many other web service which supports anchor.
